"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _overview_dashboard from './overview-dashboard.bones.json'
import _template_list from './template-list.bones.json'
import _user_list from './user-list.bones.json'

registerBones({
  "overview-dashboard": _overview_dashboard,
  "template-list": _template_list,
  "user-list": _user_list,
})
